---
title: "EDA for IoT Intrusion Detection"
output: html_notebook
---

### Data summary

```{r}
library(dplyr)

# cleans up old stuff in R
rm(list=ls())

# read in the data
data = read.csv("RT_IOT2022.csv")

# remove index column
df = select(data, -X)
```

``` {r}
# summarize the data
head(df)
#names(df)
paste("There are", dim(df)[1],
      "observations and ", dim(df)[2],
      "features.")
#glimpse(df)
#sapply(df, class)

# Checking for missing data
clean <- ifelse(complete.cases(df)==TRUE, 1, 0)
paste("There are", dim(df)[1]-sum(clean),
      "rows with missing data.")
```

``` {r}
table(sapply(df, class))
```
## Feature distributions
``` {r}
library(ggplot2)

# rename attack types
df$Attack_type <- recode(data$Attack_type,
                         MQTT_Publish="MQTT",
                         ARP_poisioning="ARP", 
                         DDOS_Slowloris="DDOS",
                         DOS_SYN_Hping="DOS",
                         Metasploit_Brute_Force_SSH="SSH",
                         NMAP_FIN_SCAN="FIN_SCAN",
                         NMAP_OS_DETECTION="OS_Detect",
                         NMAP_TCP_scan="TCP_SCAN",
                         NMAP_UDP_SCAN="UDP_SCAN",
                         NMAP_XMAS_TREE_SCAN="XMAS_SCAN")




# Create the bar chart with counts and percentage (rounded to 2 decimals) above the bars
attack_type_counts <- ggplot(df, aes(x = Attack_type)) +
  geom_bar(fill = "skyblue", color = "black") +
  geom_text(stat = "count", aes(label = paste0(after_stat(count))), 
            vjust = -0.5, size = 3) +  # Position count text
  geom_text(stat = "count", aes(label = paste0(" (", scales::percent(round(after_stat(count)/sum(after_stat(count)), 4)), ")")), 
            vjust = -2, size = 3) +  # Position percentage text
  labs(title = "Count of Observations by Attack Type", x = "Attack Type", y = "Count") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  ylim(0, 100000)

print(attack_type_counts)
```

## Relationships between variables
### Correlation
``` {r}
library(ggcorrplot)
library(dplyr)
library(GGally)

# Select only numeric or integer columns
num <- df %>%
  select_if(function(col) is.numeric(col) || is.integer(col))
``` 
``` {r}
num_columns <- ncol(num)

# Specify the number of variables to include in each correlogram
num_variables_per_correlogram <- 10

# ggcorplot version is MUCH faster, doesn't include scatterplots
# only use ggpairs version for like 5 variables
correlogram.loop <- function(df, num_variables_per_correlogram, gg.cor=TRUE) {
  num_columns = ncol(df)
  for (i in seq(1, num_columns - 1, by = num_variables_per_correlogram)) {
    # Select the columns for the current correlogram
    columns_to_include <- c(i:(i + num_variables_per_correlogram - 1))
    
    # Subset the data frame with selected columns
    subset_df <- df[, columns_to_include]
    
    if (gg.cor) {
      c2 = cor(subset_df)
      c2 <- ggcorrplot(c2,
                     type = "lower",
                     lab = TRUE,
                     lab_size = 3,
                     method = "circle",
                     colors = c("tomato2", "white", "springgreen3"),
                     title = "Correlogram",
                     ggtheme = theme_bw)
      print(c2)
    } else {
      gg.out <- ggpairs(subset_df, lower = list(continuous = "points"), diag = list(continuous = "barDiag"))
      print(gg.out)
    }
  }
}
```
#### ggcor correlograms
``` {r}
correlogram.loop(num, 10)
```
#### ggpairs correlograms
``` {r}
correlogram.loop(num[,6:20], 5, gg.cor=FALSE)
```

